local paths = {
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
	"data/entities/animals/.xml",
}